import { useMemo, useRef, useState } from 'react'

export function Sheet({title,subtitle,children,onClose,hideClose=false}){
 return <div className="sheetwrap on"><button className="scrim" aria-label="닫기" data-act="sheet-close" onClick={onClose}/><section className="sheet"><div className="grab"/><header className="sheethead"><b>{title}</b>{subtitle&&<div className="mini">{subtitle}</div>}{!hideClose&&<button className="sheetclose" data-act="sheet-close" onClick={onClose} aria-label="닫기">×</button>}</header><div className="sheetbody">{children}</div></section></div>
}

export function CirclePicker({circles,selected,onSelect,onJoin,onCreate,onClose}){
 const[code,setCode]=useState('')
 return <Sheet title="끼리 선택" subtitle="함께 쓰는 할 일 목록" onClose={onClose}><div className="pcard join-box"><h3>초대 코드로 참여</h3><p>받은 코드를 입력해 끼리에 참여합니다.</p><div className="join-row"><input className="field" value={code} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="예: KKIU-ABCD"/><button className="mbtn primary" data-act="invite-join" onClick={()=>onJoin?.(code)}>참여</button></div></div>{circles.map(c=><button className="suprow" key={c.id} onClick={()=>onSelect(c.id)}><span className="crow-check">{selected===c.id?'✓':c.emoji}</span><span className="smid"><b>{c.name}</b><span>멤버 {c.members?.length||1}명 · 진행 중 {c.tasks.filter(t=>!t.done).length}개</span></span>{c.unread>0&&<span className="circle-badge">{c.unread}</span>}<span className="out">›</span></button>)}<button className="featins" data-act="circle-new" onClick={onCreate}><span className="p">+</span>새 끼리 만들기</button></Sheet>
}

const emojiCatalog=[
 ['😀','웃음 smile happy'],['😊','미소 smile happy'],['🙂','사람 person face'],['🌿','잎 풀 자연 leaf plant nature'],['🐶','강아지 개 dog puppy'],['🐕','강아지 개 dog puppy'],['🐱','고양이 cat kitten'],['🐰','토끼 rabbit'],['🦊','여우 fox'],['🐻','곰 bear'],['🌸','꽃 벚꽃 flower blossom'],['🌹','꽃 장미 flower rose'],['🌻','꽃 해바라기 flower sunflower'],['🍊','귤 오렌지 과일 orange fruit'],['🍎','사과 과일 apple fruit'],['🍳','음식 요리 food cooking'],['🍚','음식 밥 food rice'],['☕','커피 음료 coffee drink'],['🏠','집 우리집 home house'],['✈️','여행 비행기 travel plane'],['🏕️','캠핑 여행 camp travel'],['🚲','자전거 bike bicycle'],['🎯','목표 target goal'],['🎈','풍선 축하 balloon party'],['🎮','게임 game'],['📚','책 공부 book study'],['🎵','음악 music'],['🪴','화분 식물 plant pot'],['🧺','빨래 바구니 laundry basket'],['🪁','연 kite'],['🌊','바다 파도 sea wave'],['☀️','해 태양 날씨 sun weather'],['🌳','나무 자연 tree nature'],['🧡','주황 하트 orange heart'],['🌙','달 밤 moon night'],['⭐','별 star'],['🔥','불 열정 fire'],['✨','반짝임 sparkle'],['💡','아이디어 전구 idea light'],['✅','완료 체크 done check']
]
function IdentityEditor({kind,name,setName,emoji,setEmoji,onDone,onCancel}){
 const[q,setQ]=useState('');const normalized=q.trim().toLowerCase();const shown=emojiCatalog.filter(([symbol,keys])=>!normalized||symbol.includes(normalized)||keys.toLowerCase().includes(normalized));return <div className="identity-editor"><header className="identity-editor-head"><div><span className="identity-editor-kicker">{kind==='circle'?'CIRCLE':'MY PROFILE'}</span><h3>{kind==='circle'?'끼리 설정':'내 프로필 설정'}</h3></div><button className="identity-close" data-act="modal-cancel" aria-label="닫기" onClick={onCancel}>×</button></header><div className="identity-editor-body"><label className="identity-field-label">이름</label><div className="identity-name-wrap"><span className="identity-name-preview">{emoji}</span><input className="field" value={name} onChange={e=>setName(e.target.value)}/></div><div className="identity-field-label"><span>이모지</span><span className="identity-selected">선택됨 <b>{emoji}</b></span></div><input className="field" value={q} onChange={e=>setQ(e.target.value)} placeholder="강아지, 꽃, moon, food"/><p className="identity-search-hint">한국어·영어 키워드 또는 이모지로 검색할 수 있어요.</p><div className="identity-emoji-grid">{shown.length?shown.map(([symbol])=><button type="button" className={emoji===symbol?'on':''} data-act="identity-emoji-pick" data-e={symbol} onClick={()=>setEmoji(symbol)} key={symbol}>{symbol}</button>):<div className="identity-empty">검색 결과가 없어요</div>}</div></div><footer className="identity-actions"><button type="button" className="seltxt" data-act="identity-random" onClick={()=>setEmoji(emojiCatalog[Math.floor(Math.random()*emojiCatalog.length)][0])}>🎲 랜덤</button><button type="button" className="seltxt identity-save" data-act="identity-save" onClick={onDone}>저장</button></footer></div>
}

export function CircleEditor({circle,profile,onSave,onInvite,onReorder,onLeave,onDelete,onClose}){
 const[name,setName]=useState(circle?.name||''),[emoji,setEmoji]=useState(circle?.emoji||'🌿'),[pn,setPn]=useState(profile?.name||'영롱'),[pe,setPe]=useState(profile?.emoji||'🌿'),[editing,setEditing]=useState(null),memberDrag=useRef(null)
 const save=()=>onSave({name:name.trim()||'새 끼리',emoji,profileName:pn.trim()||'나',profileEmoji:pe});const cancelEditing=()=>{if(editing==='circle'){setName(circle?.name||'');setEmoji(circle?.emoji||'🌿')}else{setPn(profile?.name||'영롱');setPe(profile?.emoji||'🌿')}setEditing(null)};const moveMember=(from,to)=>{if(!circle||from<1||to<1||to>=circle.members.length)return;const next=[...circle.members],[m]=next.splice(from,1);next.splice(to,0,m);onReorder?.(next)}
 if(!circle)return <Sheet title="새 끼리 만들기" onClose={onClose}><IdentityEditor kind="circle" name={name} setName={setName} emoji={emoji} setEmoji={setEmoji} onDone={save} onCancel={onClose}/></Sheet>
 if(editing)return <Sheet title={editing==='circle'?'끼리 설정':'내 프로필 설정'} onClose={cancelEditing}><IdentityEditor kind={editing} name={editing==='circle'?name:pn} setName={editing==='circle'?setName:setPn} emoji={editing==='circle'?emoji:pe} setEmoji={editing==='circle'?setEmoji:setPe} onDone={()=>{save();setEditing(null)}} onCancel={cancelEditing}/></Sheet>
 return <Sheet title={`${emoji} ${name}`} subtitle="끼리 관리" onClose={onClose} hideClose><div className="pcard invite-card"><h3>초대 코드 · <span className="code-chip">{circle.code||'KKIU-HOME'}</span></h3><p>이 코드를 공유하면 멤버가 들어올 수 있어요. (데모: 복사만 동작)</p><button className="rbtn" data-act="invite" onClick={()=>onInvite?.(circle.code||'KKIU-HOME')}>코드 복사 <span>⎘</span></button></div><button className="rbtn identity-setting" data-act="circle-identity-edit" onClick={()=>setEditing('circle')}><span className="mlead"><span className="mrank">{emoji}</span><span><b>끼리</b><em>{name}</em></span></span><span>편집 ›</span></button><button className="rbtn identity-setting" data-act="profile-identity-edit" onClick={()=>setEditing('profile')}><span className="mlead"><span className="mrank">{pe}</span><span><b>내 프로필</b><em>{pn}</em></span></span><span>편집 ›</span></button><div className="ghead"><span>멤버 {circle.members?.length||0}명</span></div><div className="member-order-list">{circle.members?.map((m,i)=>{const n=circle.tasks.filter(t=>!t.done&&(t.assignee||t.assignees?.[0])===m.id).length;return <div className="suprow member-order-row" data-member={m.id} key={m.id}><span className="who">{m.emoji}</span><span className="smid"><b>{m.name}{i===0?' (나)':''}</b><span>진행 중 {n}개</span></span><span className="member-handle">{i===0?'고정':<button className="member-grip" aria-label={`${m.name} 순서 변경`} onPointerDown={e=>{memberDrag.current={id:m.id,pointerId:e.pointerId};e.currentTarget.setPointerCapture(e.pointerId);e.currentTarget.closest('.member-order-row')?.classList.add('dragging')}} onPointerMove={e=>{if(!memberDrag.current||memberDrag.current.pointerId!==e.pointerId)return;const list=e.currentTarget.closest('.member-order-list'),row=list?.querySelector(`[data-member="${memberDrag.current.id}"]`),target=document.elementFromPoint(e.clientX,e.clientY)?.closest('.member-order-row');if(!row||!target||target===row||target.dataset.member===circle.members[0]?.id)return;const r=target.getBoundingClientRect();list.insertBefore(row,e.clientY<r.top+r.height/2?target:target.nextSibling)}} onPointerUp={e=>{const list=e.currentTarget.closest('.member-order-list'),order=[...(list?.querySelectorAll('.member-order-row')||[])].map(row=>row.dataset.member),next=order.map(id=>circle.members.find(member=>member.id===id)).filter(Boolean);list?.querySelector('.dragging')?.classList.remove('dragging');if(next.length===circle.members.length)onReorder?.(next);memberDrag.current=null}} onPointerCancel={e=>{e.currentTarget.closest('.member-order-list')?.querySelector('.dragging')?.classList.remove('dragging');memberDrag.current=null}} onKeyDown={e=>{if(e.key==='ArrowUp')moveMember(i,i-1);if(e.key==='ArrowDown')moveMember(i,i+1)}}>⠿</button>}</span></div>})}</div><div className="mdiv"/><button className="rbtn" data-act="circle-leave" onClick={onLeave}>나가기 <span>›</span></button>{onDelete&&<button className="rbtn danger" data-act="circle-del" onClick={onDelete}>이 끼리 삭제 <em>· 개설자만 가능</em></button>}</Sheet>
}

const startOfDay=(value)=>{const date=new Date(value);date.setHours(0,0,0,0);return date.getTime()}
const completedGroup=(iso,language)=>{const day=startOfDay(iso),now=startOfDay(Date.now()),diff=Math.round((now-day)/864e5);if(diff===0)return language==='en'?'Today':'오늘';if(diff===1)return language==='en'?'Yesterday':'어제';if(diff<7)return language==='en'?'This week':'이번 주';return language==='en'?'Earlier':'이전'}
export function CompletedSheet({tasks,members,circle,onRestore,onDelete,onClear,onClose,language='ko'}){
 const[expanded,setExpanded]=useState(null),[filter,setFilter]=useState('')
 const filtered=filter?tasks.filter(t=>(t.assignees||[t.assignee]).includes(filter)):tasks
 const labels=language==='en'?['Today','Yesterday','This week','Earlier']:['오늘','어제','이번 주','이전']
 const groups=useMemo(()=>labels.map(label=>({label,items:filtered.filter(task=>completedGroup(task.completedAt,language)===label)})).filter(group=>group.items.length),[filtered,language])
 const weekCount=tasks.filter(task=>Date.now()-new Date(task.completedAt||0).getTime()<7*864e5).length
 return <Sheet title={`✓ ${language==='en'?`Completed ${filtered.length}`:`완료됨 ${filtered.length}`}`} subtitle={language==='en'?`This week ${weekCount} · Total ${tasks.length}`:`이번 주 ${weekCount}개 · 누적 ${tasks.length}개`} onClose={onClose}>{circle&&<div className="donechips"><button className={`donechip${!filter?' on':''}`} data-act="done-filter" onClick={()=>setFilter('')}>{language==='en'?'All':'전체'}</button>{members.map(m=><button className={`donechip${filter===m.id?' on':''}`} data-act="done-filter" data-m={m.id} key={m.id} onClick={()=>setFilter(m.id)}><span className="av">{m.emoji}</span>{m.name}</button>)}</div>}{!filtered.length?<div className="empty completed-empty"><div className="empty-c"><h3>{tasks.length?(language==='en'?'No completed tasks for this member':'이 담당자의 완료 항목이 없어요'):(language==='en'?'No completed tasks yet':'아직 완료한 일이 없어요')}</h3><p>{language==='en'?'Tap a completed circle to restore its original position.':'동그라미를 다시 누르면 완료 당시 번호로 복원돼요.'}</p></div></div>:groups.map(g=><section key={g.label}><div className="ghead"><span>{g.label} · {g.items.length}</span><button data-act="sheet-clear" onClick={()=>onClear(g.items.map(t=>t.id))}>{language==='en'?'Clear':'비우기'}</button></div>{g.items.map(t=><div className={`drow${expanded===t.id?' expanded':''}`} key={t.id} data-act="sheet-expand" data-id={t.id} onClick={()=>setExpanded(expanded===t.id?null:t.id)}><button className="ck on" aria-label={`${language==='en'?'Restore':'완료 취소'}: ${t.title}`} data-act="restore" data-id={t.id} onClick={e=>{e.stopPropagation();onRestore(t.id)}}>✓</button><span className="rankc">#{(t.doneAt??0)+1}</span><span className="dtitle">{t.title}</span>{t.sourceUnread&&<i className="source-unread-dot" aria-label={language==='en'?'Unseen update':'처음 확인하는 업데이트'}/>} {circle&&<span className="who">{members.find(m=>(t.assignees||[t.assignee]).includes(m.id))?.emoji}</span>}<span className="dtime">{t.completedAt?new Date(t.completedAt).toLocaleDateString(language==='en'?'en-US':'ko-KR'):''}</span><button className="dx" aria-label={`${language==='en'?'Delete':'삭제'}: ${t.title}`} data-act="sheet-del" data-id={t.id} onClick={e=>{e.stopPropagation();onDelete(t.id)}}>×</button></div>)}</section>)}{tasks.length>0&&<button className="rbtn danger" data-act="sheet-clear" onClick={()=>onClear(tasks.map(t=>t.id))}>{language==='en'?'Clear all completed tasks':'완료 목록 전체 비우기'}</button>}</Sheet>
}

export function ConfirmDialog({title,message,danger,onCancel,onConfirm}){return <div className="modalwrap on"><button className="scrim" aria-label="취소" data-act="modal-cancel" onClick={onCancel}/><div className="modal"><h3>{title}</h3><p>{message}</p><div className="mrow"><button className="mbtn" data-act="modal-cancel" onClick={onCancel}>취소</button><button className={`mbtn ${danger?'danger':'primary'}`} data-act="modal-ok" onClick={onConfirm}>확인</button></div></div></div>}
